### ISSUE TITLE
Identify_neurons: not same result on educloud

### ISSUE THREAD

**Issue by sarahthon** [CINPLA/CA2_MEC#3]
Hi,
after spikesorting + curating in phy + saving to exdir, identify_neurons in the old repository (which runs locally) is able to find 12 cells across all 5 recordings, as you can see on notebooks/00-identify-neurons.ipynb at vemundss branch in the old repository (https://github.com/sarahthon/CA2_MEC/blob/vemundss/notebooks/00-identify-neurons.ipynb). 

When spikesorting the same five recordings (001-181220-2, 001-181220-3, 001-181220-4, 001-181220-5, 001-181220-6) on educloud (project path: Sarah/projects/hpc-social-nwb), identify_neurons in this repository only finds 6.

**Comment by lepmik** [comment]
Permission denied: '/projects/ec109/Sarah/projects/hpc-social-nwb/actions/identify-neurons/data/sessions.csv'

**Comment by alejoe91** [comment]
@sarahthon one suggestion from Mikkel is to compute templates using all waveforms. 

Is this project a conversion from an old exdir project?

**Comment by sarahthon** [comment]
@alejoe91 yes, these are converted.

**Comment by alejoe91** [comment]
I'll push a fix there, but you might need to reconvert

**Comment by alejoe91** [comment]
Ok, in this [last commit](https://github.com/CINPLA/expipe-plugin-cinpla/pull/64/commits/367f33f37b48a6c45d7a55315e93652738669591) all waveforms are extracted, so it should give a better estimate of the templates used for unit tracking

I would wait for @lepmik to deploy it on EduCloud. Is that ok?

@sarahthon just for clarification: you did not re-spikesort the recordings, right? Otherwise the mismatch could be very well due to different spike sorting outcomes

**Comment by sarahthon** [comment]
@alejoe91 I only converted + «save to NWB units» for these recordings. 

I do plan on spikesorting new actions and running identify_neurons on educloud later.

**Comment by sarahthon** [comment]
We have tested identify_neurons with the newst updates. We still don't get the same results, but I know get 7 out of the 12 cells that match locally.

**Comment by lepmik** [comment]
Then I'm out of ideas and out of time, @alejoe91 could you look into this?

**Comment by alejoe91** [comment]
@sarahthon can you try to check the old exdir templates and the new ones one by one? At least for a session. If they are exactly* the same then it must be some package versioning difference, but these would be very hard to find..
