### ISSUE TITLE
"Neuronal Population Coding" notebook bug

### ISSUE THREAD

**Issue by sarahthon** [CINPLA/CA2_MEC#4]
"Neuronal Population Coding" notebook:

When choosing "trial" decoding, it says that 'include_actions" is not defined:
![image](https://github.com/CINPLA/CA2_MEC/assets/39300702/c2d7f081-f305-4f7d-9893-0c016db9ffe1)
See the whole notebook we run locally in the old repo here: https://github.com/sarahthon/CA2_MEC/blob/vemundss/notebooks/neural-population-decoder.ipynb

However, "include_actions" is defined as it works for both social and spatial decoding. I assume there is a convergence problem in the code here: 
CA2_MEC/ca2-mec/methods.py

Can you check this out when this notebook is adjusted for NWB-data on educloud?

**Comment by nicolossus** [comment]
Fixed by cb91cc6.
